### ISSUE TITLE
demo 没有上传完全把

### ISSUE THREAD

**Issue by ChenSiWu** [HalyangDream/ShortVideo#1]

**Comment by HalyangDream** [comment]
Sorry，因为工作原因,忘记写了,你这边是很需要么

**Comment by guoshilun** [comment]
可以给个demo吗，谢谢，

**Comment by HalyangDream** [comment]
> 可以给个demo吗，谢谢，

因为是用在项目里的,跟你讲个思路吧 就是 RecyclerView+PagerSnHelper+七牛的播放器

**Comment by guoshilun** [comment]
ke

> > 可以给个demo吗，谢谢，
> 
> 因为是用在项目里的,跟你讲个思路吧 就是 RecyclerView+PagerSnHelper+七牛的播放器
好的，谢谢，
